#!/bin/bash
chown -R www-data:www-data /var/www/html/storage
chmod -R ug+rwx /var/www/html/storage
printenv | grep -v "no_proxy" >> /etc/environment
cd /var/www/html
sleep 10

echo Starting migrations
php artisan config:clear
php artisan migrate --force
php artisan cache:clear
php artisan lighthouse:clear-cache
php artisan lighthouse:cache
echo Done
exit 0
