#!/bin/bash
chown -R www-data:www-data /var/www/html/storage
chmod -R ug+rwx /var/www/html/storage
printenv | grep -v "no_proxy" >> /etc/environment
cd /var/www/html
php artisan config:clear

php artisan config:cache
php artisan route:cache
php artisan view:cache

/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
