<?php

return [
    /*
     * Application ID generated by AppStore
     */
    'app_id' => env('APPSTORE_APP_ID', ''),

    /*
     * Secret generated by AppStore
     */
    'app_secret' => env('APPSTORE_APP_SECRET', ''),

    /*
     * AppStore Secret generated by AppStore
     */
    'appstore_secret' => env('APPSTORE_SECRET', ''),
];
